from .calculator import  calculator
from .database_webscraper import database_webscraper
from .image_gen import generate_image
from .web import research
from .RAG import SQL_RAG
from .image_gen2 import generate_image2
from .video import video_gen
from .internet_search import web_search
from .pdfsummary import pdf_summary
from .get_data import get_data
